// ─── Deterministic Formal-Letter Intelligence ───────────────────────────────
//
// This module is a hand-curated English → Hindi vocabulary of ~550 words and
// ~110 sentence-level phrase templates covering the full spectrum of Indian
// formal correspondence: government letters, bank letters, school/college
// letters, legal notices, RTI applications, complaints, leave applications,
// NOCs, certificates, municipal complaints, health/safety requests, and more.
//
// Merging precedence (general is LOWEST — domain seeds always win):
//   GENERAL_HI_TOKENS → SEED_HI_TOKENS → HI_TOKENS_EXTRA → overlay
//   GENERAL_PHRASES → FORMAL_PHRASES → HI_PHRASES → overlay
//
// A morphology pass in translateHindiToken (translate.ts) extends each
// content-word entry to cover inflected forms: plural (-s/-es/-ies),
// past-tense (-ed/-d/-ied), and gerund (-ing).  This single layer
// multiplies the effective dictionary from ~550 base forms to ~1500+ surface
// forms — so the word-level floor almost never falls through to phonetic
// transliteration.
// ─────────────────────────────────────────────────────────────────────────────

// ─── 1. WORD-LEVEL DICTIONARY ──────────────────────────────────────────────

export const GENERAL_HI_TOKENS: Record<string, string> = {

  // ═══ PRONOUNS ═══
  "me":          "मुझे",
  "i":           "मैं",
  "my":          "मेरा",
  "mine":        "मेरा",
  "we":          "हम",
  "us":          "हमें",
  "our":         "हमारा",
  "you":         "आप",
  "your":        "आपका",
  "he":          "वह",
  "him":         "उसे",
  "his":         "उसका",
  "she":         "वह",
  "her":         "उसकी",
  "they":        "वे",
  "them":        "उन्हें",
  "their":       "उनका",
  "its":         "उसका",
  "myself":      "स्वयं",
  "himself":     "स्वयं",
  "herself":     "स्वयं",
  "themselves":  "स्वयं",
  "ourselves":   "स्वयं",

  // ═══ DEMONSTRATIVES / INTERROGATIVES ═══
  "this":        "यह",
  "that":        "वह",
  "these":       "ये",
  "those":       "वे",
  "which":       "जो",
  "who":         "जो",
  "whom":        "जिसे",
  "whose":       "जिसका",
  "what":        "क्या",
  "when":        "जब",
  "where":       "जहाँ",
  "why":         "क्यों",
  "how":         "कैसे",
  "wherever":    "जहाँ भी",
  "whenever":    "जब भी",

  // ═══ ARTICLES / PREPOSITIONS / CONJUNCTIONS ═══
  "the":         "",
  "a":           "",
  "an":          "",
  "of":          "का",
  "to":          "को",
  "in":          "में",
  "on":          "पर",
  "at":          "पर",
  "by":          "द्वारा",
  "with":        "के साथ",
  "from":        "से",
  "for":         "के लिए",
  "and":         "एवं",
  "or":          "या",
  "but":         "लेकिन",
  "if":          "यदि",
  "so":          "इसलिए",
  "as":          "जैसा",
  "than":        "की तुलना में",
  "nor":         "न",
  "yet":         "फिर भी",

  // ═══ FUNCTION WORDS ═══
  "not":         "नहीं",
  "no":          "नहीं",
  "never":       "कभी नहीं",
  "please":      "कृपया",
  "kindly":      "कृपया",
  "also":        "भी",
  "too":         "भी",
  "only":        "केवल",
  "just":        "केवल",
  "even":        "भी",
  "still":       "अभी भी",
  "already":     "पहले ही",
  "very":        "अत्यंत",
  "quite":       "काफ़ी",
  "much":        "अधिक",
  "more":        "अधिक",
  "most":        "सबसे अधिक",
  "some":        "कुछ",
  "any":         "कोई",
  "all":         "सभी",
  "every":       "प्रत्येक",
  "each":        "प्रत्येक",
  "both":        "दोनों",
  "either":      "कोई एक",
  "neither":     "कोई नहीं",
  "none":        "कोई नहीं",
  "nothing":     "कुछ नहीं",
  "something":   "कुछ",
  "everything":  "सब कुछ",
  "nobody":      "कोई नहीं",
  "everyone":    "सभी",
  "many":        "अनेक",
  "few":         "कुछ",
  "several":     "अनेक",
  "various":     "विभिन्न",
  "another":     "दूसरा",
  "other":       "अन्य",
  "others":      "अन्य",

  // ═══ ADVERBS ═══
  "therefore":   "अतः",
  "hence":       "अतः",
  "thus":        "इस प्रकार",
  "however":     "तथापि",
  "moreover":    "इसके अतिरिक्त",
  "furthermore": "इसके अतिरिक्त",
  "besides":     "इसके अलावा",
  "although":    "हालाँकि",
  "though":      "हालाँकि",
  "despite":     "के बावजूद",
  "instead":     "इसके बजाय",
  "otherwise":   "अन्यथा",
  "meanwhile":   "इस बीच",
  "finally":     "अंततः",
  "firstly":     "सबसे पहले",
  "secondly":    "दूसरे",
  "lastly":      "अंत में",
  "namely":      "अर्थात्",
  "hereby":      "इसके द्वारा",
  "herein":      "इसमें",
  "hereinafter": "इसके बाद",
  "thereafter":  "उसके बाद",
  "therein":     "उसमें",
  "whereby":     "जिसके द्वारा",
  "wherein":     "जिसमें",
  "currently":   "वर्तमान में",
  "presently":   "वर्तमान में",
  "recently":    "हाल ही में",
  "immediately": "तत्काल",
  "especially":  "विशेषकर",
  "particularly": "विशेषकर",
  "commonly":    "सामान्यतः",
  "generally":   "सामान्यतः",
  "usually":     "प्रायः",
  "often":       "अक्सर",
  "sometimes":   "कभी-कभी",
  "rarely":      "शायद ही कभी",
  "always":      "हमेशा",
  "together":    "साथ में",
  "separately":  "अलग-अलग",
  "equally":     "समान रूप से",
  "merely":      "केवल",
  "simply":      "केवल",
  "purely":      "पूर्णतः",
  "mainly":      "मुख्यतः",
  "largely":     "मुख्यतः",
  "partly":      "आंशिक रूप से",
  "fully":       "पूर्णतः",
  "truly":       "वास्तव में",
  "properly":    "उचित रूप से",
  "duly":        "यथाविधि",
  "hopefully":   "आशा है",
  "certainly":   "निश्चित रूप से",
  "naturally":   "स्वाभाविक रूप से",
  "briefly":     "संक्षेप में",
  "actually":    "वास्तव में",
  "generously":  "उदारता से",
  "warmly":      "सादर",
  "respectfully": "सविनय",
  "sincerely":   "सादर",

  // ═══ TIME ═══
  "today":       "आज",
  "tomorrow":    "आने वाला कल",
  "yesterday":   "बीता हुआ कल",
  "now":         "अब",
  "then":        "तब",
  "before":      "से पहले",
  "after":       "के बाद",
  "during":      "के दौरान",
  "while":       "जबकि",
  "until":       "जब तक",
  "till":        "तक",
  "since":       "से",
  "someday":     "कभी न कभी",
  "forthwith":   "तत्काल",
  "henceforth":  "इसके बाद",
  "aforesaid":   "उपर्युक्त",
  "hereupon":    "तत्पश्चात्",
  "hereto":      "इसमें",

  // ═══ QUANTITIES / NUMBERS ═══
  "one":         "एक",
  "two":         "दो",
  "three":       "तीन",
  "four":        "चार",
  "five":        "पाँच",
  "six":         "छह",
  "seven":       "सात",
  "eight":       "आठ",
  "nine":        "नौ",
  "ten":         "दस",
  "twenty":      "बीस",
  "thirty":      "तीस",
  "forty":       "चालीस",
  "fifty":       "पचास",
  "hundred":     "सौ",
  "thousand":    "हज़ार",
  "lakh":        "लाख",
  "crore":       "करोड़",
  "first":       "प्रथम",
  "second":      "द्वितीय",
  "third":       "तृतीय",
  "fourth":      "चतुर्थ",
  "fifth":       "पंचम",
  "once":        "एक बार",
  "twice":       "दो बार",

  // ═══ COMMON VERBS (base forms — morphology covers inflections) ═══
  "request":     "अनुरोध",
  "apply":       "आवेदन",
  "submit":      "प्रस्तुत",
  "send":        "भेजना",
  "receive":     "प्राप्त",
  "give":        "देना",
  "take":        "लेना",
  "make":        "बनाना",
  "do":          "करना",
  "get":         "प्राप्त",
  "provide":     "प्रदान",
  "issue":       "जारी",
  "grant":       "प्रदान",
  "approve":     "अनुमोदित",
  "reject":      "अस्वीकृत",
  "accept":      "स्वीकृत",
  "consider":    "विचार",
  "examine":     "जाँच",
  "verify":      "सत्यापित",
  "check":       "जाँच",
  "inform":      "सूचित",
  "notify":      "सूचित",
  "intimate":    "सूचित",
  "convey":      "संप्रेषित",
  "communicate": "संपर्क",
  "attach":      "संलग्न",
  "enclose":     "संलग्न",
  "forward":     "अग्रेषित",
  "return":      "वापस",
  "reply":       "उत्तर",
  "respond":     "प्रतिक्रिया",
  "contact":     "संपर्क",
  "meet":        "बैठक",
  "start":       "शुरू",
  "begin":       "शुरू",
  "end":         "समाप्त",
  "finish":      "पूर्ण",
  "complete":    "पूर्ण",
  "continue":    "जारी",
  "stop":        "रोकना",
  "close":       "बंद",
  "open":        "खोलना",
  "increase":    "वृद्धि",
  "decrease":    "कमी",
  "reduce":      "कम",
  "improve":     "सुधार",
  "change":      "परिवर्तन",
  "modify":      "संशोधित",
  "revise":      "संशोधन",
  "update":      "अद्यतन",
  "cancel":      "निरस्त",
  "postpone":    "स्थगित",
  "extend":      "विस्तारित",
  "renew":       "नवीनीकृत",
  "allow":       "अनुमत",
  "permit":      "अनुमत",
  "prohibit":    "निषिद्ध",
  "ban":         "प्रतिबंधित",
  "require":     "आवश्यक",
  "demand":      "माँग",
  "need":        "आवश्यकता",
  "want":        "चाहता",
  "wish":        "इच्छा",
  "hope":        "आशा",
  "expect":      "अपेक्षा",
  "wait":        "प्रतीक्षा",
  "try":         "प्रयास",
  "manage":      "प्रबंधन",
  "handle":      "संभालना",
  "solve":       "हल",
  "resolve":     "समाधान",
  "fix":         "ठीक",
  "repair":      "मरम्मत",
  "build":       "निर्माण",
  "install":     "स्थापित",
  "remove":      "हटाना",
  "delete":      "मिटाना",
  "add":         "जोड़ना",
  "include":     "शामिल",
  "exclude":     "बाहर",
  "join":        "शामिल",
  "separate":    "अलग",
  "divide":      "विभाजित",
  "distribute":  "वितरित",
  "deliver":     "वितरित",
  "collect":     "संग्रह",
  "pay":         "भुगतान",
  "spend":       "खर्च",
  "save":        "बचत",
  "earn":        "अर्जित",
  "borrow":      "उधार लेना",
  "lend":        "उधार देना",
  "owe":         "बकाया",
  "deduct":      "कटौती",
  "refund":      "धनवापसी",
  "reimburse":   "प्रतिपूर्ति",
  "sign":        "हस्ताक्षर",
  "fill":        "भरना",
  "write":       "लिखना",
  "read":        "पढ़ना",
  "print":       "मुद्रित",
  "publish":     "प्रकाशित",
  "announce":    "घोषित",
  "declare":     "घोषित",
  "confirm":     "पुष्टि",
  "deny":        "अस्वीकार",
  "refuse":      "इनकार",
  "agree":       "सहमत",
  "disagree":    "असहमत",
  "support":     "समर्थन",
  "oppose":      "विरोध",
  "object":      "आपत्ति",
  "complain":    "शिकायत",
  "apologize":   "क्षमा",
  "thank":       "धन्यवाद",
  "appreciate":  "सराहना",
  "praise":      "प्रशंसा",
  "blame":       "दोष",
  "help":        "सहायता",
  "assist":      "सहयोग",
  "cooperate":   "सहयोग",
  "participate": "भाग",
  "attend":      "उपस्थिति",
  "absent":      "अनुपस्थित",
  "arrive":      "आगमन",
  "reach":       "पहुँचना",
  "stay":        "ठहरना",
  "live":        "निवास",
  "reside":      "निवास",
  "move":        "स्थानांतरण",
  "relocate":    "स्थानांतरण",
  "go":          "जाना",
  "come":        "आना",
  "leave":       "अवकाश",
  "depart":      "प्रस्थान",
  "enter":       "प्रवेश",
  "exit":        "निकास",
  "bring":       "लाना",
  "carry":       "ले जाना",
  "keep":        "रखना",
  "protect":     "सुरक्षा",
  "defend":      "बचाव",
  "attack":      "हमला",
  "fight":       "संघर्ष",
  "struggle":    "संघर्ष",
  "succeed":     "सफल",
  "fail":        "विफल",
  "achieve":     "उपलब्धि",
  "gain":        "लाभ",
  "lose":        "हानि",
  "find":        "खोज",
  "search":      "तलाश",
  "know":        "जानना",
  "understand":  "समझ",
  "realize":     "समझ",
  "remember":    "स्मरण",
  "forget":      "भूलना",
  "think":       "विचार",
  "believe":     "विश्वास",
  "trust":       "भरोसा",
  "doubt":       "संदेह",
  "seem":        "प्रतीत",
  "appear":      "प्रकट",
  "happen":      "घटित",
  "occur":       "घटित",
  "exist":       "अस्तित्व",
  "become":      "बनना",
  "grow":        "वृद्धि",
  "develop":     "विकास",
  "progress":    "प्रगति",
  "decline":     "अस्वीकार",
  "remain":      "बना रहना",
  "depend":      "निर्भर",
  "rely":        "निर्भर",
  "relate":      "संबंधित",
  "belong":      "संबंधित",
  "consist":     "शामिल",
  "contain":     "शामिल",
  "involve":     "शामिल",
  "select":      "चयन",
  "choose":      "चयन",
  "decide":      "निर्णय",
  "determine":   "निर्धारित",
  "establish":   "स्थापित",
  "operate":     "संचालित",
  "function":    "कार्य",
  "maintain":    "बनाए रखना",
  "retain":      "बनाए रखना",
  "preserve":    "संरक्षण",
  "adapt":       "अनुकूल",
  "adopt":       "अपनाना",
  "embrace":     "अपनाना",
  "dismiss":     "बर्खास्त",
  "terminate":   "समाप्त",
  "abolish":     "निरस्त",
  "amend":       "संशोधित",
  "enforce":     "लागू",
  "execute":     "कार्यान्वित",
  "implement":   "कार्यान्वित",
  "perform":     "कार्यान्वित",
  "undertake":   "कार्यान्वित",
  "compensate":  "मुआवज़ा",
  "punish":      "दंडित",
  "penalize":    "दंडित",
  "reward":      "पुरस्कृत",
  "nurture":     "पोषण",
  "promote":     "पदोन्नत",
  "demote":      "पदावनत",
  "nominate":    "नामांकित",
  "resign":      "त्यागपत्र",
  "retire":      "सेवानिवृत्त",
  "recruit":     "भर्ती",
  "employ":      "नियोजित",
  "fire":        "बर्खास्त",
  "train":       "प्रशिक्षित",
  "educate":     "शिक्षित",
  "teach":       "शिक्षण",
  "learn":       "अध्ययन",
  "practice":    "अभ्यास",
  "research":    "अनुसंधान",
  "study":       "अध्ययन",
  "explore":     "अन्वेषण",
  "discover":    "खोज",
  "invent":      "आविष्कार",
  "create":      "निर्माण",
  "generate":    "उत्पन्न",
  "produce":     "उत्पादन",
  "manufacture": "विनिर्माण",
  "export":      "निर्यात",
  "import":      "आयात",
  "trade":       "व्यापार",
  "buy":         "क्रय",
  "sell":        "विक्रय",
  "lease":       "पट्टा",
  "rent":        "किराया",
  "mortgage":    "गिरवी",
  "pledge":      "बंधक",
  "govern":      "शासन",
  "rule":        "शासन",
  "administer":  "प्रशासन",
  "regulate":    "विनियमन",
  "legislate":   "विधान",
  "authorise":   "अधिकृत",
  "empower":     "सशक्त",
  "delegate":    "प्रतिनियुक्त",
  "intervene":   "हस्तक्षेप",
  "negotiate":   "वार्ता",
  "settle":      "निपटान",
  "arbitrate":   "मध्यस्थता",
  "mediate":     "मध्यस्थता",
  "adjudicate":  "निर्णय",
  "heal":        "उपचार",
  "cure":        "उपचार",
  "diagnose":    "निदान",
  "treat":       "उपचार",
  "prescribe":   "निर्धारित",

  // ═══ NOUNS — ADMINISTRATION / OFFICE ═══
  "application": "आवेदन",
  "letter":      "पत्र",
  "document":    "दस्तावेज़",
  "copy":        "प्रति",
  "original":    "मूल",
  "signature":   "हस्ताक्षर",
  "date":        "दिनांक",
  "subject":     "विषय",
  "reference":   "संदर्भ",
  "enclosure":   "संलग्नक",
  "annexure":    "अनुलग्नक",
  "attachment":  "संलग्नक",
  "concern":     "संबंधित",
  "department":  "विभाग",
  "ministry":    "मंत्रालय",
  "government":  "सरकार",
  "administration": "प्रशासन",
  "authority":   "प्राधिकरण",
  "authorities": "प्राधिकरण",
  "manager":     "प्रबंधक",
  "supervisor":  "पर्यवेक्षक",
  "engineer":    "अभियंता",
  "doctor":      "चिकित्सक",
  "hospital":    "अस्पताल",
  "school":      "विद्यालय",
  "college":     "महाविद्यालय",
  "university":  "विश्वविद्यालय",
  "master":      "स्नातकोत्तर",
  "bachelor":    "स्नातक",
  "student":     "छात्र",
  "teacher":     "शिक्षक",
  "employee":    "कर्मचारी",
  "employer":    "नियोक्ता",
  "worker":      "श्रमिक",
  "labour":      "श्रम",
  "labor":       "श्रम",
  "salary":      "वेतन",
  "wages":       "मजदूरी",
  "payment":     "भुगतान",
  "amount":      "राशि",
  "money":       "धनराशि",
  "bill":        "बिल",
  "invoice":     "बिल",
  "receipt":     "रसीद",
  "account":     "खाता",
  "bank":        "बैंक",
  "loan":        "ऋण",
  "interest":    "ब्याज",
  "tax":         "कर",
  "fee":         "शुल्क",
  "fine":        "जुर्माना",
  "deposit":     "जमा",
  "withdrawal":  "निकासी",
  "balance":     "शेष",
  "budget":      "बजट",
  "cost":        "लागत",
  "price":       "मूल्य",
  "expense":     "खर्च",
  "income":      "आय",
  "profit":      "लाभ",
  "loss":        "हानि",
  "property":    "संपत्ति",
  "land":        "भूमि",
  "house":       "मकान",
  "building":    "भवन",
  "room":        "कक्ष",
  "door":        "दरवाज़ा",
  "window":      "खिड़की",
  "water":       "पानी",
  "electricity": "बिजली",
  "power":       "विद्युत",
  "road":        "सड़क",
  "drain":       "नाली",
  "garbage":     "कचरा",
  "cleanliness": "सफ़ाई",
  "repair_n":    "मरम्मत",
  "maintenance": "रखरखाव",
  "construction": "निर्माण",
  "safety":      "सुरक्षा",
  "danger":      "खतरा",
  "risk":        "जोखिम",
  "accident":    "दुर्घटना",
  "injury":      "चोट",
  "death":       "मृत्यु",
  "health":      "स्वास्थ्य",
  "medical":     "चिकित्सा",
  "treatment":   "इलाज",
  "medicine":    "दवा",
  "disease":     "रोग",
  "illness":     "बीमारी",
  "fever":       "बुखार",
  "holiday":     "अवकाश",
  "vacation":    "अवकाश",
  "duty":        "कर्तव्य",
  "shift":       "पाली",
  "work":        "कार्य",
  "job":         "नौकरी",
  "service":     "सेवा",
  "post":        "पद",
  "promotion":   "पदोन्नति",
  "transfer":    "स्थानांतरण",
  "retirement":  "सेवानिवृत्ति",
  "resignation": "त्यागपत्र",
  "appointment": "नियुक्ति",
  "joining":     "कार्यग्रहण",
  "increment":   "वेतन वृद्धि",
  "allowance":   "भत्ता",
  "bonus":       "बोनस",
  "pension":     "पेंशन",
  "gratuity":    "ग्रेच्युइटी",
  "insurance":   "बीमा",
  "claim":       "दावा",
  "compensation": "मुआवज़ा",
  "benefit":     "लाभ",
  "scheme":      "योजना",
  "policy":      "नीति",
  "regulation":  "विनियम",
  "law":         "कानून",
  "act":         "अधिनियम",
  "clause":      "खंड",
  "article":     "अनुच्छेद",
  "constitution": "संविधान",
  "court":       "न्यायालय",
  "judge":       "न्यायाधीश",
  "lawyer":      "अधिवक्ता",
  "case":        "मामला",
  "complaint":   "शिकायत",
  "police":      "पुलिस",
  "crime":       "अपराध",
  "theft":       "चोरी",
  "fraud":       "धोखाधड़ी",
  "corruption":  "भ्रष्टाचार",
  "inquiry":     "जाँच",
  "investigation": "अन्वेषण",
  "report":      "रिपोर्ट",
  "certificate": "प्रमाणपत्र",
  "license":     "लाइसेंस",
  "permission":  "अनुमति",
  "approval":    "अनुमोदन",
  "sanction":    "स्वीकृति",
  "identity":    "पहचान",
  "photograph":  "फोटो",
  "address":     "पता",
  "residence":   "निवास",
  "resident":    "निवासी",
  "family":      "परिवार",
  "father":      "पिता",
  "mother":      "माता",
  "wife":        "पत्नी",
  "husband":     "पति",
  "son":         "पुत्र",
  "daughter":    "पुत्री",
  "brother":     "भाई",
  "sister":      "बहन",
  "children":    "बच्चे",
  "friend":      "मित्र",
  "neighbor":    "पड़ोसी",
  "person":      "व्यक्ति",
  "people":      "लोग",
  "man":         "पुरुष",
  "woman":       "महिला",
  "name":        "नाम",
  "age":         "आयु",
  "birth":       "जन्म",
  "gender":      "लिंग",
  "nationality": "राष्ट्रीयता",
  "religion":    "धर्म",
  "category":    "श्रेणी",
  "qualification": "योग्यता",
  "experience":  "अनुभव",
  "skill":       "कौशल",
  "training":    "प्रशिक्षण",
  "education":   "शिक्षा",
  "degree":      "उपाधि",
  "exam":        "परीक्षा",
  "interview":   "साक्षात्कार",
  "meeting":     "बैठक",
  "agenda":      "कार्यसूची",
  "minutes":     "कार्यवृत्त",
  "discussion":  "चर्चा",
  "decision":    "निर्णय",
  "proposal":    "प्रस्ताव",
  "suggestion":  "सुझाव",
  "opinion":     "राय",
  "view":        "विचार",
  "information": "सूचना",
  "details":     "विवरण",
  "record":      "अभिलेख",
  "register":    "पंजिका",
  "file":        "फ़ाइल",
  "data":        "आँकड़े",
  "list":        "सूची",
  "table":       "तालिका",
  "form":        "प्रपत्र",
  "format":      "प्रारूप",
  "sample":      "नमूना",
  "example":     "उदाहरण",
  "draft":       "मसौदा",
  "final":       "अंतिम",
  "summary":     "सारांश",
  "description": "विवरण",
  "statement":   "कथन",
  "declaration": "घोषणा",
  "affidavit":   "शपथपत्र",
  "undertaking": "वचनपत्र",
  "agreement":   "समझौता",
  "contract":    "अनुबंध",
  "tender":      "निविदा",
  "purchase":    "क्रय",
  "sale":        "विक्रय",
  "supply":      "आपूर्ति",
  "stock":       "भंडार",
  "material":    "सामग्री",
  "equipment":   "उपकरण",
  "machine":     "मशीन",
  "tool":        "औज़ार",
  "vehicle":     "वाहन",
  "car":         "कार",
  "ticket":      "टिकट",
  "travel":      "यात्रा",
  "journey":     "यात्रा",
  "trip":        "दौरा",
  "tour":        "भ्रमण",
  "visit":       "भ्रमण",
  "arrival":     "आगमन",
  "departure":   "प्रस्थान",
  "delay":       "विलंब",
  "late":        "देर",
  "early":       "शीघ्र",
  "soon":        "शीघ्र",
  "urgent":      "अत्यावश्यक",
  "emergency":   "आपातकाल",
  "important":   "महत्वपूर्ण",
  "necessary":   "आवश्यक",
  "essential":   "आवश्यक",
  "available":   "उपलब्ध",
  "sufficient":  "पर्याप्त",
  "adequate":    "पर्याप्त",
  "additional":  "अतिरिक्त",
  "special":     "विशेष",
  "particular":  "विशिष्ट",
  "specific":    "विशिष्ट",
  "general":     "सामान्य",
  "normal":      "सामान्य",
  "regular":     "नियमित",
  "irregular":   "अनियमित",
  "temporary":   "अस्थायी",
  "permanent":   "स्थायी",
  "incomplete":  "अपूर्ण",
  "correct":     "सही",
  "wrong":       "गलत",
  "true":        "सत्य",
  "false":       "असत्य",
  "new":         "नया",
  "old":         "पुराना",
  "young":       "युवा",
  "big":         "बड़ा",
  "small":       "छोटा",
  "large":       "बड़ा",
  "long":        "लंबा",
  "high":        "उच्च",
  "low":         "निम्न",
  "good":        "अच्छा",
  "bad":         "बुरा",
  "best":        "सर्वश्रेष्ठ",
  "better":      "बेहतर",
  "easy":        "आसान",
  "difficult":   "कठिन",
  "hard":        "कठिन",
  "possible":    "संभव",
  "impossible":  "असंभव",
  "clear":       "स्पष्ट",
  "sure":        "निश्चित",
  "free":        "निःशुल्क",
  "closed":      "बंद",
  "full":        "पूर्ण",
  "empty":       "खाली",
  "whole":       "पूरा",
  "half":        "आधा",
  "part":        "भाग",
  "total":       "कुल",
  "single":      "एकल",
  "next":        "अगला",
  "previous":    "पिछला",
  "following":   "निम्नलिखित",
  "above":       "उपर्युक्त",
  "below":       "निम्नलिखित",
  "same":        "समान",
  "different":   "भिन्न",
  "right":       "अधिकार",
  "left":        "बायाँ",
  "center":      "केंद्र",
  "middle":      "बीच",
  "top":         "शीर्ष",
  "bottom":      "तल",
  "inside":      "अंदर",
  "outside":     "बाहर",

  // ═══ TIME PERIODS ═══
  "day":         "दिन",
  "night":       "रात",
  "morning":     "प्रातः",
  "evening":     "सायं",
  "afternoon":   "दोपहर",
  "week":        "सप्ताह",
  "month":       "माह",
  "year":        "वर्ष",
  "decade":      "दशक",
  "century":     "शताब्दी",
  "daily":       "दैनिक",
  "weekly":      "साप्ताहिक",
  "monthly":     "मासिक",
  "quarterly":   "त्रैमासिक",
  "yearly":      "वार्षिक",
  "annual":      "वार्षिक",

  // ═══ GEOGRAPHY / TITLES ═══
  "village":     "गाँव",
  "town":        "नगर",
  "city":        "शहर",
  "state":       "राज्य",
  "country":     "देश",
  "world":       "विश्व",
  "north":       "उत्तर",
  "south":       "दक्षिण",
  "east":        "पूर्व",
  "west":        "पश्चिम",
  "district":    "जिला",
  "block":       "प्रखंड",
  "blocks":      "ब्लॉक",
  "tehsil":      "तहसील",
  "mandal":      "मंडल",
  "region":      "क्षेत्र",
  "province":    "प्रांत",
  "colony":      "कॉलोनी",
  "ward":        "वार्ड",
  "municipality": "नगरपालिका",
  "council":     "परिषद्",
  "parliament":  "संसद",
  "assembly":    "विधानसभा",
  "senate":      "राज्य सभा",
  "president":   "राष्ट्रपति",
  "prime_minister": "प्रधानमंत्री",
  "minister":    "मंत्री",
  "secretary":   "सचिव",
  "director":    "निदेशक",
  "officer":     "अधिकारी",
  "officers":    "अधिकारी",
  "chief":       "मुख्य",
  "head":        "प्रमुख",
  "chairman":    "अध्यक्ष",
  "member":      "सदस्य",
  "shri":        "श्री",
  "smt":         "श्रीमती",
  "smt.":        "श्रीमती",
  "mrs":         "श्रीमती",
  "mr":          "श्री",
  "dr":          "डॉ.",
  "honble":      "माननीय",
  "honorable":   "माननीय",
  "respected":   "आदरणीय",
  "dear":        "आदरणीय",
  "sir":         "महोदय",
  "madam":       "महोदया",
  "mohd":        "मोहम्मद",
  "janab":       "जनाब",

  // ═══ ADDRESSES / PLACE WORDS ═══
  "pin":         "पिन",
  "pincode":     "पिन कोड",
  "postcode":    "पिन कोड",
  "telephone":   "दूरभाष",
  "mobile":      "मोबाइल",
  "phone":       "दूरभाष",
  "email":       "ईमेल",
  "website":     "वेबसाइट",
  "fax":         "फैक्स",
  "std":         "एसटीडी",
  "po":          "पी.ओ.",
  "ps":          "पी.एस.",

  // ═══ LEGAL / FINANCIAL ═══
  "appeal":      "अपील",
  "petition":    "याचिका",
  "writ":        "रिट याचिका",
  "verdict":     "निर्णय",
  "judgement":   "निर्णय",
  "sentence":    "सज़ा",
  "penalty":     "दंड",
  "bail":        "जमानत",
  "warrant":     "वारंट",
  "summons":     "समन",
  "subpoena":    "समन",
  "evidence":    "साक्ष्य",
  "witness":     "गवाह",
  "testimony":   "गवाही",
  "oath":        "शपथ",
  "swear":       "शपथ",
  "promise":     "वचन",
  "commitment":  "प्रतिबद्धता",
  "responsibility": "उत्तरदायित्व",
  "liability":   "दायित्व",
  "obligation":  "बाध्यता",
  "accountability": "जवाबदेही",
  "justice":     "न्याय",
  "equality":    "समानता",
  "freedom":     "स्वतंत्रता",
  "liberty":     "स्वतंत्रता",
  "democracy":   "लोकतंत्र",
  "secular":     "धर्मनिरपेक्ष",

  // ═══ HEALTH / SAFETY ═══
  "clinic":      "चिकित्सालय",
  "nurse":       "नर्स",
  "patient":     "रोगी",
  "ambulance":   "एम्बुलेंस",
  "pharmacy":    "फ़ार्मेसी",
  "surgery":     "शल्यक्रिया",
  "operation":   "ऑपरेशन",
  "injection":   "इंजेक्शन",
  "vaccination": "टीकाकरण",
  "epidemic":    "महामारी",
  "pandemic":    "महामारी",
  "quarantine":  "पृथक-वास",
  "sanitation":  "स्वच्छता",
  "hygiene":     "स्वच्छता",
  "pollution":   "प्रदूषण",
  "environment": "पर्यावरण",
  "flood":       "बाढ़",
  "earthquake":  "भूकंप",
  "cyclone":     "चक्रवात",
  "drought":     "सूखा",
  "disaster":    "आपदा",
  "relief":      "राहत",
  "rescue":      "उद्धार",
  "evacuation":  "निकासी",
  "shelter":     "शरणस्थल",
  "camp":        "शिविर",
  "refugee":     "शरणार्थी",
  "victim":      "पीड़ित",
  "survivor":    "उत्तरजीवी",

  // ═══ COMMON ABBREVIATIONS ═══
  "etc":         "इत्यादि",
  "etc.":        "इत्यादि",
  "ie":          "अर्थात्",
  "i.e.":        "अर्थात्",
  "eg":          "उदाहरणार्थ",
  "e.g.":        "उदाहरणार्थ",
  "viz":         "अर्थात्",
  "viz.":        "अर्थात्",
  "ex":          "पूर्व",
  "ex.":         "पूर्व",
  "vs":          "बनाम",
  "vs.":         "बनाम",
  "v":           "बनाम",
  "qr":          "आवास",
  "qr.":         "आवास",
  "pwd":         "लोक निर्माण विभाग",
  "cpwd":        "केंद्रीय लोक निर्माण विभाग",
  "rti":         "सूचना का अधिकार",
  "fir":         "प्राथमिकी",
  "gst":         "वस्तु एवं सेवा कर",
  "income_tax":  "आयकर",
  "pan":         "स्थायी खाता संख्या",
  "aadhaar":     "आधार",
  "epf":         "कर्मचारी भविष्य निधि",
  "esi":         "कर्मचारी राज्य बीमा",
  "bpp":         "आधारभूत वेतन",
  "da":          "महँगाई भत्ता",
  "hra":         "मकान किराया भत्ता",
  "ta":          "यात्रा भत्ता",
  "cca":          "नगर क्षतिपूर्ति भत्ता",
  "nps":         "राष्ट्रीय पेंशन योजना",
  "gif":         "सरकारी बीमा कोष",
  "gis":         "सरकारी बीमा योजना",
  "pli":         "डाक जीवन बीमा",
  "rpli":        "ग्रामीण डाक जीवन बीमा",

  // ── Legal, financial, and administrative vocabulary (auto-expanded)
  "ab initio": "शुरू से",
  "abeyance": "लंबित",
  "abrogation": "निरस्तीकरण",
  "accountant": "लेखाकार",
  "accrual": "अर्जन",
  "ad hoc": "अस्थायी",
  "ad valorem": "मूल्यानुसार",
  "adhere": "पालन करना",
  "adhered": "पालन किया",
  "adjournment": "स्थगन",
  "adjudication": "निर्णय",
  "adjustment": "समायोजन",
  "administrative": "प्रशासनिक",
  "aforementioned": "उपरोक्त",
  "alleged": "कथित",
  "alleviate": "कम करना",
  "allocation": "आवंटन",
  "amended": "संशोधित",
  "amending": "संशोधन",
  "amicus curiae": "न्यायालय मित्र",
  "annexed": "संलग्न",
  "annulment": "शून्यकरण",
  "appended": "संलग्न",
  "appendix": "परिशिष्ट",
  "appropriation": "उपबंध",
  "arbitration": "मध्यस्थता",
  "arrears": "बकाया",
  "audi alteram partem": "दूसरे पक्ष को भी सुनो",
  "audit": "लेखापरीक्षा",
  "audited": "ऑडिट किया हुआ",
  "auditor": "लेखापरीक्षक",
  "authorized": "अधिकृत",
  "bona fide": "सद्भावपूर्ण",
  "breach": "उल्लंघन",
  "breached": "उल्लंघन किया",
  "bureaucratic": "नौकरशाही",
  "cadre": "कैडर",
  "cancellation": "रद्दीकरण",
  "caveat emptor": "खरीददार सावधान",
  "certification": "प्रमाणन",
  "circular": "परिपत्र",
  "cited": "उद्धृत",
  "citing": "उद्धृत करते हुए",
  "commensurate": "अनुरूप",
  "compendium": "संकलन",
  "competency": "योग्यता",
  "competent": "सक्षम",
  "compliance": "अनुपालन",
  "comptroller": "लेखापरीक्षक",
  "concession": "रियासत",
  "conciliation": "समझौता",
  "conclusive": "निर्णायक",
  "concurrent": "समवर्ती",
  "conducive": "अनुकूल",
  "congenial": "अनुकूल",
  "consensus": "सहमति",
  "consolidated": "समेकित",
  "constituted": "गठित",
  "construed": "व्याख्यायित",
  "consultation": "परामर्श",
  "contingency": "आकस्मिकता",
  "contingent": "आकस्मिक",
  "contravene": "उल्लंघन करना",
  "contravention": "उल्लंघन",
  "controller": "नियंत्रक",
  "correspondence": "पत्राचार",
  "corrigendum": "शुद्धि",
  "corroborate": "पुष्टि करना",
  "cumulative": "संचयी",
  "curtailment": "संक्षेपण",
  "custodial": "अभिरक्षा",
  "dated": "दिनांकित",
  "de facto": "वास्तविक",
  "de jure": "कानूनी",
  "deduction": "कटौती",
  "deferral": "विलंब",
  "definitive": "अंतिम",
  "delegated": "प्रत्यायोजित",
  "deliberation": "विचार-विमर्श",
  "dereliction": "कर्तव्य-परायणता",
  "designated": "निर्धारित",
  "detriment": "हानि",
  "detrimental": "हानिकारक",
  "diminution": "ह्रास",
  "directive": "निर्देश",
  "directives": "निर्देश",
  "disbursement": "वितरण",
  "disciplinary": "अनुशासनात्मक",
  "discrepancies": "विसंगतियाँ",
  "discrepancy": "विसंगति",
  "discretion": "विवेक",
  "discretionary": "विवेकाधीन",
  "dispensation": "विशेष छूट",
  "disqualification": "अपात्रता",
  "dissent": "असहमति",
  "dissolution": "विघटन",
  "effective": "प्रभावी",
  "effective date": "प्रभावी तिथि",
  "eligibility": "पात्रता",
  "emoluments": "वेतन भत्ते",
  "empowered": "सशक्त",
  "enclosed": "संलग्न",
  "endorsement": "अनुमोदन",
  "enforceable": "प्रवर्तनीय",
  "enjoined": "आदेशित",
  "enquiry": "जाँच",
  "entitled": "अधिकृत",
  "entitlement": "अधिकार",
  "enumerate": "सूचीबद्ध करना",
  "enumerated": "सूचीबद्ध",
  "enumerating": "सूचीबद्ध करते हुए",
  "equivalent": "समकक्ष",
  "erroneous": "गलत",
  "erroneously": "गलती से",
  "evince": "प्रकट करना",
  "evinced": "प्रकट किया",
  "ex gratia": "कृपा से",
  "ex officio": "पदेन",
  "ex parte": "एकपक्षीय",
  "exchequer": "राजकोष",
  "exemption": "छूट",
  "expedient": "उचित",
  "expedite": "शीघ्र करना",
  "expenditure": "व्यय",
  "extraneous": "बाहरी",
  "extrinsic": "बाह्य",
  "facilitate": "सहज बनाना",
  "fiduciary": "संप्रुत्य",
  "fitness": "फिटनेस",
  "force majeure": "अप्रत्याशित घटना",
  "furnished": "प्रदान किया",
  "furnishing": "प्रदान करना",
  "gazette": "राजपत्र",
  "grievance": "शिकायत",
  "hereafter": "इसके बाद",
  "hereunder": "इसके अंतर्गत",
  "herewith": "इसके साथ",
  "hierarchical": "पदानुक्रमित",
  "immunity": "प्रतिरक्षा",
  "impediment": "बाधा",
  "implementing": "कार्यान्वयन",
  "impugned": "चुनौतीपूर्ण",
  "in lieu": "के स्थान पर",
  "in perpetuity": "सदैव",
  "indemnity": "क्षतिपूर्ति",
  "inimical": "प्रतिकूल",
  "inspection": "निरीक्षण",
  "inter alia": "इनके अतिरिक्त",
  "interim": "अंतरिम",
  "intrinsic": "आंतरिक",
  "invoke": "आह्वान करना",
  "invoked": "आह्वान किया",
  "invoking": "आह्वान करते हुए",
  "jurisdiction": "क्षेत्राधिकार",
  "jurisdictional": "क्षेत्राधिकार संबंधी",
  "latitude": "स्वतंत्रता",
  "liaising": "संपर्क करना",
  "liaison": "संपर्क अधिकारी",
  "mandated": "अनिवार्य",
  "mandatory": "अनिवार्य",
  "mediation": "मध्यस्थता",
  "memorandum": "स्मरण पत्र",
  "ministerial": "मंत्रालय",
  "mitigate": "शमन करना",
  "modus operandi": "कार्यविधि",
  "monetary": "आर्थिक",
  "negligence": "लापरवाही",
  "nemo judex in causa sua": "स्वयं अपने मामले में न्यायाधीश नहीं",
  "non-compliance": "अनुपालन न होना",
  "non-compliant": "अनुपालन न करने वाला",
  "non-functional": "गैर-कार्यात्मक",
  "noted": "अभिलिखित",
  "notification": "अधिसूचना",
  "noting": "अभिलेख",
  "notional": "काल्पनिक",
  "notwithstanding": "इसके बावजूद",
  "nullification": "निरस्तीकरण",
  "obviate": "दूर करना",
  "operative": "संचालन",
  "operative date": "प्रभावी तिथि",
  "ordinance": "अध्यादेश",
  "overpayment": "अधिक भुगतान",
  "overruled": "अस्वीकृत",
  "panel": "पैनल",
  "pecuniary": "आर्थिक",
  "per annum": "प्रति वर्ष",
  "per capita": "प्रति व्यक्ति",
  "per diem": "प्रतिदिन",
  "perquisites": "भत्ते",
  "postponement": "स्थगन",
  "preclude": "बाहर करना",
  "predicated": "आधारित",
  "prejudice": "पूर्वाग्रह",
  "prejudicial": "हानिकारक",
  "preliminary": "प्रारंभिक",
  "prerogative": "विशेषाधिकार",
  "prescribed": "निर्धारित",
  "prima facie": "प्रथम दृष्टया",
  "privilege": "विशेषाधिकार",
  "pro bono": "निःशुल्क सेवा",
  "pro rata": "आनुपातिक",
  "proceedings": "कार्यवाही",
  "proportionate": "आनुपातिक",
  "prospective": "भावी",
  "provision": "प्रावधान",
  "provisional": "अस्थायी",
  "proviso": "शर्त",
  "quid pro quo": "बदले में",
  "ratification": "अनुसमर्थन",
  "reaffirm": "पुनर्पुष्टि करना",
  "reaffirmed": "पुनर्पुष्टि की गई",
  "recalculated": "पुनर्गणित",
  "reciprocal": "पारस्परिक",
  "recovery": "वसूली",
  "recurring": "आवर्ती",
  "redress": "निवारण",
  "redressal": "निवारण",
  "registrar": "रजिस्ट्रार",
  "regulations": "विनियम",
  "reimbursement": "प्रतिपूर्ति",
  "reiterate": "दोहराना",
  "reiterated": "दोहराया गया",
  "reiterating": "दोहराते हुए",
  "relaxation": "छूट",
  "remittance": "प्रेषण",
  "remitted": "प्रेषित",
  "remuneration": "पारिश्रमिक",
  "rescission": "अभिनिवेश",
  "resolution": "संकल्प",
  "retained": "बरकरार रखा गया",
  "retrospective": "पूर्वव्यापी",
  "revenue": "राजस्व",
  "revising": "संशोधन",
  "revisited": "पुनर्विचार किया",
  "revisiting": "पुनर्विचार",
  "revocation": "निरस्तीकरण",
  "salaried": "वेतनभोगी",
  "sanctioned": "स्वीकृत",
  "scrutiny": "जाँच",
  "secretarial": "सचिवालय",
  "sine qua non": "अनिवार्य शर्त",
  "status quo": "वर्तमान स्थिति",
  "stipulated": "शर्त रखी गई",
  "sub judice": "न्यायालय में विचाराधीन",
  "substantiate": "प्रमाणित करना",
  "subsumed": "समाहित",
  "subsuming": "समाहित करते हुए",
  "sui generis": "अद्वितीय",
  "suo motu": "स्वयं",
  "superintendent": "अधीक्षक",
  "supersede": "स्थानांतरित करना",
  "superseded": "स्थानांतरित",
  "superseding": "स्थानांतरित करते हुए",
  "supervisory": "पर्यवेक्षी",
  "suspension": "निलंबन",
  "termination": "समाप्ति",
  "territorial": "क्षेत्रीय",
  "thereof": "उसका",
  "thereunder": "उसके अंतर्गत",
  "treasurer": "कोषाध्यक्ष",
  "treasury": "कोष",
  "tribunal": "न्यायाधिकरण",
  "ultra vires": "अधिकार से बाहर",
  "under": "के अंतर्गत",
  "undermentioned": "निम्नलिखित",
  "undersecretary": "अवर सचिव",
  "upheld": "बरकरार",
  "verification": "सत्यापन",
  "vigilance": "सतर्कता",
  "violated": "उल्लंघन किया",
  "violation": "उल्लंघन",
  "whereas": "जबकि",
  "whereupon": "जिस पर",
  "withheld": "रोका गया",
  "withholding": "रोक",


  // ── Additional legal/admin vocabulary (batch 2)
  "absorbed": "अवशोषित",
  "addressee": "पताधारी",
  "adjudicatory": "निर्णायक",
  "amendment": "संशोधन",
  "appellate": "अपीली",
  "attested": "प्रमाणित",
  "burdensome": "बोझिल",
  "certified": "प्रमाणित",
  "competence": "योग्यता",
  "compliant": "अनुपालनकारी",
  "cumbersome": "जटिल",
  "cursory": "संक्षिप्त",
  "documents": "दस्तावेज़",
  "employees": "कर्मचारियों",
  "exhaustive": "व्यापक",
  "financial": "वित्तीय",
  "gratuitous": "निःशुल्क",
  "indemnification": "क्षतिपूर्ति",
  "indemnified": "क्षतिपूर्तित",
  "intricate": "जटिल",
  "liaised": "संपर्क किया",
  "malfeasance": "दुराचरण",
  "onerous": "भारी",
  "perfunctory": "लीपापोती",
  "personnel": "कर्मचारी",
  "proceeding": "कार्यवाही",
  "provisionally": "अस्थायी रूप से",
  "provisions": "प्रावधान",
  "reimbursed": "प्रतिपूर्ति की गई",
  "resigned": "त्यागपत्र दिया",
  "retiring": "सेवानिवृत्त",
  "transferred": "स्थानांतरित",
  "transfers": "स्थानांतरण",
  "voluminous": "विस्तृत",
  "voluntary": "स्वैच्छिक",

};

// ─── 2. SENTENCE-LEVEL PHRASE TEMPLATES ─────────────────────────────────────
// These are general-purpose formal-letter phrases (NOT letter-specific like
// the FORMAL_PHRASES in translate.ts).  They fire BEFORE the word-level
// dictionary, so a sentence like "I beg to state that" becomes
// "सविनय निवेदन है कि" without any individual word needing to be known.
// ─────────────────────────────────────────────────────────────────────────────

export const GENERAL_FORMAL_PHRASES: Array<[RegExp, string]> = [
  // ── Openings / submissions ──
  [/i beg to (?:state|say|submit|inform) that/gi, "सविनय निवेदन है कि"],
  [/i beg to (?:state|say|submit|inform)/gi, "सविनय निवेदन है"],
  [/i beg to (?:submit|state) this/gi, "सविनय प्रस्तुत है"],
  [/this is to (?:state|inform|certify|bring to your notice) that/gi, "यह सूचित किया जाता है कि"],
  [/this is to (?:state|inform|notify) you that/gi, "आपको सूचित किया जाता है कि"],
  [/this is to (?:certify|certified) that/gi, "यह प्रमाणित किया जाता है कि"],
  [/it is (?:hereby )?(?:stated|submitted|informed|noted|declared|certified) that/gi, "यह सूचित किया जाता है कि"],
  [/it is to inform (?:you )?that/gi, "यह सूचित किया जाता है कि"],
  [/i would like to (?:inform|state|submit|request|bring to your notice) that/gi, "मैं सूचित करना चाहता हूँ कि"],
  [/i wish to (?:inform|state|submit|request|bring to your notice) that/gi, "मैं सूचित करना चाहता हूँ कि"],
  [/i am (?:writing to )?(?:inform|request|bring to your notice) that/gi, "मैं सूचित कर रहा हूँ कि"],
  [/i am directed to (?:inform|state|submit) that/gi, "मुझे निर्देश दिया गया है कि"],
  [/i am (?:writing to )?(?:request|apply) for/gi, "मैं हेतु आवेदन कर रहा हूँ"],
  [/subject\s*:\s*/gi, "विषय: "],

  // ── Respectful requests ──
  [/you are (?:respectfully|kindly|hereby) (?:requested|informed|directed|invited|notified) to/gi, "आपसे विनम्रतापूर्वक अनुरोध है कि"],
  [/you are (?:respectfully|kindly|hereby) (?:requested|informed|directed|invited|notified)/gi, "आपसे विनम्रतापूर्वक अनुरोध है"],
  [/kindly (?:do|take|arrange|consider|grant|approve|sanction|allow|permit|arrange) the needful/gi, "कृपया आवश्यक कार्रवाई करें"],
  [/do the needful/gi, "आवश्यक कार्रवाई करें"],
  [/kindly (?:do the needful|take necessary action|take appropriate action)/gi, "कृपया आवश्यक कार्रवाई करें"],
  [/take (?:necessary|appropriate|required|urgent) (?:action|steps|note|cognizance)/gi, "आवश्यक कार्रवाई करें"],
  [/arrange (?:for )?(?:the )?(?:necessary|required|appropriate) (?:action|steps|facilities|arrangements)/gi, "आवश्यक व्यवस्था करें"],
  [/would you (?:kindly|please) (?:do|take|arrange|consider)/gi, "कृपया"],
  [/please (?:do|take|arrange|consider|grant|approve|sanction|allow|permit)/gi, "कृपया"],
  [/may (?:it|this) be (?:kindly )?(?:treated as|considered as)/gi, "कृपया इसे माना जाए"],
  [/may (?:i|we) (?:kindly be )?(?:be allowed|be permitted|request|have)/gi, "मुझे अनुमति दी जाए"],

  // ── Standard closings ──
  [/thank you in advance/gi, "पूर्व में धन्यवाद"],
  [/thanks in advance/gi, "पूर्व में धन्यवाद"],
  [/thank you very much/gi, "अत्यंत धन्यवाद"],
  [/awaiting your (?:kind )?(?:reply|response|orders|instructions|decision)/gi, "आपके उत्तर की प्रतीक्षा है"],
  [/looking forward to your (?:kind )?(?:reply|response)/gi, "आपके उत्तर की प्रतीक्षा कर रहा हूँ"],
  [/early (?:action|reply|response) (?:in the matter|in this regard|on this) (?:is|will be) (?:highly )?(?:appreciated|gratefully)/gi, "शीघ्र उत्तर की कामना है"],
  [/without further delay/gi, "बिना किसी विलंब के"],
  [/as soon as possible/gi, "यथाशीघ्र"],
  [/at the earliest/gi, "शीघ्रातिशीघ्र"],
  [/with all haste/gi, "शीघ्रातिशीघ्र"],
  [/at your earliest convenience/gi, "आपकी सुविधानुसार शीघ्र"],

  // ── References / citations ──
  [/with (?:due )?reference to/gi, "के संदर्भ में"],
  [/with reference to your (?:letter|note|order|communication|memorandum)/gi, "आपके पत्र के संदर्भ में"],
  [/in (?:reference|regard) to/gi, "के संबंध में"],
  [/in (?:this|the above|the said) regard/gi, "इस संबंध में"],
  [/with regard to/gi, "के संबंध में"],
  [/in pursuance of/gi, "के अंतर्गत"],
  [/in (?:compliance|pursuance) with/gi, "के अनुपालन में"],
  [/in accordance with/gi, "के अनुसार"],
  [/as per/gi, "के अनुसार"],
  [/according to/gi, "के अनुसार"],

  // ── Time / causal ──
  [/due to/gi, "के कारण"],
  [/because of/gi, "के कारण"],
  [/owing to/gi, "के कारण"],
  [/on account of/gi, "के कारण"],
  [/as a result of/gi, "के परिणामस्वरूप"],
  [/in spite of/gi, "के बावजूद"],
  [/instead of/gi, "के स्थान पर"],
  [/apart from/gi, "के अलावा"],
  [/in addition to/gi, "के साथ-साथ"],
  [/prior to/gi, "से पहले"],
  [/subsequent to/gi, "के बाद"],
  [/with effect from/gi, "से प्रभावी"],
  [/in case of/gi, "की स्थिति में"],
  [/in the event of/gi, "की स्थिति में"],
  [/on behalf of/gi, "की ओर से"],
  [/for the (?:benefit|purpose|sake|use|purpose) of/gi, "के लिए"],
  [/for want of/gi, "अभाव में"],
  [/with a view to/gi, "दृष्टिकोण से"],
  [/with a view to/gi, "उद्देश्य से"],
  [/for the purpose of/gi, "उद्देश्य से"],
  [/with regard to/gi, "के संबंध में"],

  // ── Specific formal patterns ──
  [/no (?:objection )?certificate/gi, "अनापत्ति प्रमाणपत्र"],
  [/character certificate/gi, "चरित्र प्रमाणपत्र"],
  [/bonafide certificate/gi, "अभिप्रमाण पत्र"],
  [/experience certificate/gi, "अनुभव प्रमाणपत्र"],
  [/relieving letter/gi, "स्थानांतरण पत्र"],
  [/appointment letter/gi, "नियुक्ति पत्र"],
  [/offer letter/gi, "नियुक्ति पत्र"],
  [/salary slip/gi, "वेतन पर्ची"],
  [/pay slip/gi, "वेतन पर्ची"],
  [/leave application/gi, "अवकाश आवेदन"],
  [/casual leave/gi, "आकस्मिक अवकाश"],
  [/earned leave/gi, "अर्जित अवकाश"],
  [/medical leave/gi, "चिकित्सकीय अवकाश"],
  [/maternity leave/gi, "मातृत्व अवकाश"],
  [/paternity leave/gi, "पितृत्व अवकाश"],
  [/privilege leave/gi, "विशेषाधिकार अवकाश"],
  [/half day leave/gi, "आधे दिन का अवकाश"],
  [/one day leave/gi, "एक दिन का अवकाश"],

  // ── Negative chains ──
  [/does not/gi, "नहीं करता"],
  [/do not/gi, "नहीं करते"],
  [/did not/gi, "नहीं किया"],
  [/will not/gi, "नहीं करेगा"],
  [/shall not/gi, "नहीं करेगा"],
  [/would not/gi, "नहीं करेगा"],
  [/could not/gi, "नहीं कर सका"],
  [/should not/gi, "नहीं करना चाहिए"],
  [/cannot/gi, "नहीं कर सकता"],
  [/must not/gi, "नहीं करना चाहिए"],
  [/may not/gi, "नहीं कर सकता"],
  [/might not/gi, "नहीं कर सकता"],
  [/is not/gi, "नहीं है"],
  [/are not/gi, "नहीं हैं"],
  [/was not/gi, "नहीं था"],
  [/were not/gi, "नहीं थे"],
  [/has not/gi, "नहीं है"],
  [/have not/gi, "नहीं है"],
  [/had not/gi, "नहीं था"],
  [/not yet/gi, "अभी तक नहीं"],
  [/neither nor/gi, "न और न"],

  // ── Positive auxiliary chains ──
  [/has been/gi, "रहा है"],
  [/have been/gi, "रहे हैं"],
  [/had been/gi, "रहा था"],
  [/is being/gi, "किया जा रहा है"],
  [/are being/gi, "किया जा रहा है"],
  [/was being/gi, "किया जा रहा था"],
  [/will be/gi, "होगा"],
  [/shall be/gi, "होगा"],
  [/would be/gi, "होगा"],
  [/can be/gi, "हो सकता है"],
  [/could be/gi, "हो सकता है"],
  [/may be/gi, "हो सकता है"],
  [/might be/gi, "हो सकता है"],
  [/must be/gi, "होना चाहिए"],
  [/should be/gi, "होना चाहिए"],
  [/ought to be/gi, "होना चाहिए"],
  [/there is/gi, "है"],
  [/there are/gi, "हैं"],
  [/there was/gi, "था"],
  [/there were/gi, "थे"],
  [/it is/gi, "यह है"],

  // ── Common verbs as phrases ──
  [/i am/gi, "मैं हूँ"],
  [/i was/gi, "मैं था"],
  [/i have/gi, "मेरे पास है"],
  [/i had/gi, "मेरे पास था"],
  [/i will/gi, "मैं करूँगा"],
  [/i shall/gi, "मैं करूँगा"],
  [/i would/gi, "मैं करता"],
  [/i can/gi, "मैं कर सकता हूँ"],
  [/you are/gi, "आप हैं"],
  [/you were/gi, "आप थे"],
  [/he is/gi, "वह है"],
  [/she is/gi, "वह है"],
  [/they are/gi, "वे हैं"],
  [/we are/gi, "हम हैं"],
  [/we were/gi, "हम थे"],

  // ── Under instructions ──
  [/under instructions from/gi, "के निर्देशानुसार"],
  [/under orders from/gi, "के आदेशानुसार"],
  [/as directed by/gi, "के निर्देशानुसार"],
  [/as per orders of/gi, "के आदेशानुसार"],
  [/as per the (?:orders|instructions|directions|guidelines) of/gi, "के अनुसार"],
  [/under intimation to/gi, "को सूचना देते हुए"],
  [/for information and necessary action/gi, "सूचना एवं आवश्यक कार्रवाई हेतु"],
  [/copy forwarded to/gi, "प्रतिलिपि"],
  [/copy to/gi, "प्रतिलिपि"],
  [/encl:/gi, "संलग्नक:",
  ],

  // ── Leave / dates ──
  [/date of birth/gi, "जन्म तिथि"],
  [/joining date/gi, "कार्यग्रहण तिथि"],
  [/date of joining/gi, "कार्यग्रहण तिथि"],
  [/last date/gi, "अंतिम तिथि"],
  [/due date/gi, "नियत तिथि"],
  [/effective date/gi, "प्रभावी तिथि"],
  [/date of retirement/gi, "सेवानिवृत्ति तिथि"],
  [/date of superannuation/gi, "सेवानिवृत्ति तिथि"],
  [/period of (?:service|employment)/gi, "सेवा अवधि"],
  [/length of service/gi, "सेवा अवधि"],
  [/working hours/gi, "कार्य समय"],
  [/office hours/gi, "कार्यालय समय"],
  [/working days/gi, "कार्य दिवस"],
  [/public holiday/gi, "सार्वजनिक अवकाश"],
  [/gazetted holiday/gi, "राजपत्रित अवकाश"],
  [/national holiday/gi, "राष्ट्रीय अवकाश"],

  // ── Address / heading patterns ──
  [/respected sir,/gi, "आदरणीय महोदय,"],
  [/respected madam,/gi, "आदरणीय महोदया,"],
  [/dear sir,/gi, "आदरणीय महोदय,"],
  [/dear madam,/gi, "आदरणीय महोदया,"],
  [/dear sir or madam,/gi, "आदरणीय महोदय/महोदया,"],
  [/to,$/im, "सेवा में,"],
  [/kind attention of/gi, "कृपया ध्यान दें"],
  [/kind attention/gi, "कृपया ध्यान"],

  // ── Formal verb phrases ──
  [/is hereby (?:declared|notified|informed|confirmed|directed|ordered|sanctioned|granted|approved|declared)/gi, "यहाँ घोषित किया जाता है"],
  [/is (?:hereby )?(?:requested|directed|instructed|ordered)/gi, "यहाँ निर्देशित किया जाता है"],
  [/is (?:hereby )?(?:notified|informed|declared|confirmed)/gi, "यहाँ सूचित किया जाता है"],
  [/is (?:hereby )?(?:sanctioned|approved|granted|allowed|permitted)/gi, "यहाँ स्वीकृत किया जाता है"],
  [/has been (?:sanctioned|approved|granted|allowed|permitted)/gi, "स्वीकृत कर दिया गया है"],
  [/is being (?:processed|considered|examined|reviewed|evaluated|investigated)/gi, "विचाराधीन है"],
  [/has been (?:processed|considered|examined|reviewed|evaluated)/gi, "विचार किया गया है"],
  [/is under (?:consideration|review|examination|process)/gi, "विचाराधीन है"],
  [/remains pending/gi, "लंबित है"],
  [/is pending/gi, "लंबित है"],
  [/was (?:rejected|declined|refused|denied|dismissed)/gi, "अस्वीकृत कर दिया गया"],
  [/has been (?:rejected|declined|refused|denied|dismissed)/gi, "अस्वीकृत कर दिया गया है"],

  // ── Financial / administrative ──
  [/with effect from/gi, "से प्रभावी"],
  [/w\.e\.f\.?/gi, "से प्रभावी"],
  [/until further orders/gi, "आदेशानुसार"],
  [/until further notice/gi, "अग्रिम आदेश तक"],
  [/with immediate effect/gi, "तत्काल प्रभाव से"],
  [/on (?:payment of|deposit of|furnishing of)/gi, "का भुगतान करने पर"],
  [/on production of/gi, "प्रस्तुत करने पर"],
  [/subject to verification/gi, "सत्यापन के अधीन"],
  [/subject to (?:the )?(?:conditions|rules|regulations|approval)/gi, "की शर्तों के अधीन"],
  [/as per (?:the )?(?:rules|regulations|guidelines|procedures|norms|terms)/gi, "के अनुसार"],
  [/in the interest of/gi, "के हित में"],
  [/in public interest/gi, "जनहित में"],
  [/in larger public interest/gi, "व्यापक जनहित में"],
  [/in national interest/gi, "राष्ट्रीय हित में"],
  // ── CMPFO / Government / Official phrases (critical for quality) ──
  // These fire in BOTH hindiTranslateLine AND transliterateProseToHindi
  [/the estate officer/gi, "संपदा अधिकारी"],
  [/coal mines provident fund organisation/gi, "कोयला खान भविष्य निधि संगठन"],
  [/coal mines provident fund/gi, "कोयला खान भविष्य निधि"],
  [/coal mines/gi, "कोयला खान"],
  [/provident fund/gi, "भविष्य निधि"],
  [/regional office/gi, "क्षेत्रीय कार्यालय"],
  [/west bengal/gi, "पश्चिम बंगाल"],
  [/regional commissioner/gi, "क्षेत्रीय आयुक्त"],
  [/copy forwarded for information and necessary action to/gi, "सूचना एवं आवश्यक कार्रवाई हेतु प्रतिलिपि भेजी जाती है:"],
  [/copy forwarded for information/gi, "सूचना हेतु प्रतिलिपि"],
  [/for information and necessary action to/gi, "सूचना एवं आवश्यक कार्रवाई हेतु"],
  [/for information and necessary action/gi, "सूचना एवं आवश्यक कार्रवाई हेतु"],
  [/working as/gi, "के रूप में कार्यरत"],
  [/in this office/gi, "इस कार्यालय में"],
  [/i am presently residing at/gi, "मैं वर्तमान में निवास कर रहा हूँ"],
  [/presently residing/gi, "वर्तमान में निवास कर रहा हूँ"],
  [/above-mentioned quarters/gi, "उपर्युक्त आवास"],
  [/above-mentioned/gi, "उपर्युक्त"],
  [/along with my family/gi, "अपने परिवार के साथ"],
  [/along with/gi, "के साथ"],
  [/however,?/gi, "हालाँकि,"],
  [/the quarters remain unattended/gi, "आवास बिना देखभाल के रह जाता है"],
  [/without any family member or other responsible person present/gi, "बिना किसी परिवार के सदस्य या अन्य जिम्मेदार व्यक्ति के उपस्थित"],
  [/without any family member/gi, "बिना किसी परिवार के सदस्य के"],
  [/i wish to bring to your kind notice/gi, "मैं आपके संज्ञान में लाना चाहता हूँ कि"],
  [/i wish to bring to your notice/gi, "मैं आपके संज्ञान में लाना चाहता हूँ कि"],
  [/have reportedly occurred/gi, "घटित हुई हैं"],
  [/reportedly occurred/gi, "घटित हुई हैं"],
  [/in the recent past/gi, "हाल के दिनों में"],
  [/bachelor staff members/gi, "अविवाहित कर्मचारी सदस्य"],
  [/bachelor staff/gi, "अविवाहित कर्मचारी"],
  [/i am unable to depend on them/gi, "मैं उन पर निर्भर नहीं हो सकता"],
  [/as they come and go as per their own convenience/gi, "क्योंकि वे अपनी सुविधानुसार आते-जाते हैं"],
  [/come and go as per their own convenience/gi, "अपनी सुविधानुसार आते-जाते हैं"],
  [/under no obligation/gi, "कोई बाध्यता नहीं है"],
  [/i therefore remain apprehensive regarding/gi, "इसलिए मैं चिंतित हूँ"],
  [/remain apprehensive regarding/gi, "की चिंता है"],
  [/in view of the above/gi, "उपरोक्त को देखते हुए"],
  [/in view of/gi, "को देखते हुए"],
  [/i would request that/gi, "अनुरोध है कि"],
  [/would be grateful if/gi, "कृपया"],
  [/at the earliest/gi, "शीघ्रातिशीघ्र"],
  [/security measures/gi, "सुरक्षा उपाय"],
  [/security guard/gi, "सुरक्षा गार्ड"],
  [/street lighting/gi, "सड़क प्रकाश व्यवस्था"],
  [/adequate street lighting/gi, "पर्याप्त सड़क प्रकाश व्यवस्था"],
  [/residential blocks/gi, "आवासीय ब्लॉक"],
  [/staff quarters/gi, "कर्मचारी आवास"],
  [/incidents of theft/gi, "चोरी की घटनाएँ"],
  [/incidents of/gi, "की घटनाएँ"],
  [/theft/gi, "चोरी"],
  [/vicinity/gi, "आसपास"],
  [/night hours/gi, "रात्रि के समय"],
  [/night security guard/gi, "रात्रि सुरक्षा गार्ड"],
  [/on leave/gi, "छुट्टी पर"],
  [/away from the quarters/gi, "आवास से दूर"],
  [/temporarily away from their quarters/gi, "अस्थायी रूप से अपने आवास से दूर"],
  [/ensuring the safety and well-being/gi, "सुरक्षा और कल्याण सुनिश्चित करना"],
  [/safety and well-being of the residents/gi, "निवासियों की सुरक्षा और कल्याण"],
  [/suitable action could be taken at the earliest/gi, "शीघ्रातिशीघ्र उचित कार्रवाई की जा सके"],
  [/yours faithfully/gi, "भवदीय"],
  [/yours sincerely/gi, "भवदीय"],
  [/yours truly/gi, "भवदीय"],
  [/with kind regards/gi, "सादर शुभकामनाओं सहित"],
  [/best regards/gi, "शुभकामनाएँ"],
  [/safeguard my quarters and belongings/gi, "मेरे आवास और संपत्ति की रक्षा"],
  [/safeguard/gi, "सुरक्षा"],
  [/belongings/gi, "संपत्ति"],
  [/apprehensive/gi, "चिंतित"],
  [/deployment/gi, "तैनाती"],
  [/installation/gi, "स्थापना"],
  [/colony/gi, "कॉलोनी"],
  [/residing in the colony/gi, "कॉलोनी में निवास कर रहे"],
  [/residents/gi, "निवासी"],
  [/residential/gi, "आवासीय"],
  [/particularly during/gi, "विशेषकर"],
  [/sir,?/gi, "महोदय,"],
  [/madam,?/gi, "महोदया,"],
  [/thanking you/gi, "धन्यवाद"],
  [/thank you/gi, "धन्यवाद"],
];

// ─── 3. MORPHOLOGY SAFE-ZONE ────────────────────────────────────────────────
// Words that look like they could be stemmed to a short Hindi word but
// shouldn't.  Used by the morphology pass in translateHindiToken to skip
// stripping when the base form would produce a dangerous collision.
// ─────────────────────────────────────────────────────────────────────────────
export const MORPH_EXCLUDE_BASES = new Set([
  "us", "is", "am", "be", "do", "go", "no", "so", "or",
]);
